
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 rustic_chair.gltf --transform 
Files: rustic_chair.gltf [4.88MB] > rustic_chair-transformed.glb [854.87KB] (82%)
Author: Araon (https://sketchfab.com/araon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rustic-chair-77afa26a76614fc2b8ed845024af0b58
Title: Rustic chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rustic_chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.lambert7SG} position={[-0.276, -0.454, -0.99]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/rustic_chair-transformed.glb')
