/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 headphone.gltf --transform 
Files: headphone.gltf [12.6MB] > headphone-transformed.glb [822.64KB] (93%)
Author: AndreiVNK (https://sketchfab.com/AndreiVNK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sony-mdr-7506-headphones-05735b74d3524f00b648231138122a28
Title: Sony MDR-7506 Headphones
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
export default function Model(props) {
  const { nodes, materials } = useGLTF('/headphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Headphone__pasted__headphones1_0.geometry} material={materials.pasted__headphones1} scale={0.01} />
      <mesh geometry={nodes.L_wire_Wire_0.geometry} material={materials.Wire} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/headphone-transformed.glb')
